### ISSUE TITLE
public (and member-only?) profile READMEs

### ISSUE THREAD

**Issue by fopinappb** [surface-security/.github#1]
### Related software versions

-

### Description

Just wanted to leave this suggestion somewhere :)

Profile READMEs also work for organizations:
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

It'd be nice to open https://github.com/surface-security/ and get a quick overview of what the organization (and its repositories / Surface) is about ❤️ 

### Use cases

-

**Comment by gsilvapt** [comment]
Yea, agree. Adding the main project to track this work and try to get it prioritized soon.
I'll also be creating a `guidelines` to contain generic rules/guides on how to contribute to the whole ecosystem: specify our preferred work method (feature branch), release methods (leverage git tags), work prioritisation and so on.

**Comment by fopina** [comment]
Good point, there could be a global CONTRIBUTING.md and have the individual ones only mention build/setup stuff, specific to each 👌

**Comment by gsilvapt** [comment]
I started some of that yesterday. More to come by end of the week but feel
free to let me know your feedback.

**Comment by gsilvapt** [comment]
Based on the above and all documentation added last month, are we okay with closing this issue?

**Comment by fopina** [comment]
Definitely, thank you!
